# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fogot_password_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 80, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 91, 20))
        self.label_2.setObjectName("label_2")
        self.login_input_line = QtWidgets.QLineEdit(Dialog)
        self.login_input_line.setGeometry(QtCore.QRect(120, 80, 113, 20))
        self.login_input_line.setObjectName("login_input_line")
        self.code_input_line = QtWidgets.QLineEdit(Dialog)
        self.code_input_line.setGeometry(QtCore.QRect(120, 160, 113, 20))
        self.code_input_line.setObjectName("code_input_line")
        self.send_code_button = QtWidgets.QPushButton(Dialog)
        self.send_code_button.setGeometry(QtCore.QRect(250, 80, 75, 23))
        self.send_code_button.setObjectName("send_code_button")
        self.check_code_button = QtWidgets.QPushButton(Dialog)
        self.check_code_button.setGeometry(QtCore.QRect(250, 190, 75, 23))
        self.check_code_button.setObjectName("check_code_button")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 81, 20))
        self.label_3.setObjectName("label_3")
        self.new_password_line = QtWidgets.QLineEdit(Dialog)
        self.new_password_line.setGeometry(QtCore.QRect(120, 190, 113, 20))
        self.new_password_line.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new_password_line.setObjectName("new_password_line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Your login:"))
        self.label_2.setText(_translate("Dialog", "Code form email:"))
        self.send_code_button.setText(_translate("Dialog", "Send code"))
        self.check_code_button.setText(_translate("Dialog", "Change pass"))
        self.label_3.setText(_translate("Dialog", " New password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
