# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'friend_request.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.accept_buton = QtWidgets.QPushButton(Dialog)
        self.accept_buton.setGeometry(QtCore.QRect(40, 260, 75, 23))
        self.accept_buton.setObjectName("accept_buton")
        self.deny_button = QtWidgets.QPushButton(Dialog)
        self.deny_button.setGeometry(QtCore.QRect(290, 260, 75, 23))
        self.deny_button.setObjectName("deny_button")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 120, 131, 16))
        self.label.setObjectName("label")
        self.friend_login_label = QtWidgets.QLabel(Dialog)
        self.friend_login_label.setGeometry(QtCore.QRect(170, 90, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.friend_login_label.setFont(font)
        self.friend_login_label.setObjectName("friend_login_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.accept_buton.setText(_translate("Dialog", "Accept"))
        self.deny_button.setText(_translate("Dialog", "Deny"))
        self.label.setText(_translate("Dialog", "Friend request from:"))
        self.friend_login_label.setText(_translate("Dialog", "friend__login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
