# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Client\gui\qt_des\incomming_call_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.login = QtWidgets.QLabel(Dialog)
        self.login.setGeometry(QtCore.QRect(60, 70, 81, 21))
        self.login.setObjectName("login")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 70, 141, 21))
        self.label_2.setObjectName("label_2")
        self.accept_button = QtWidgets.QPushButton(Dialog)
        self.accept_button.setGeometry(QtCore.QRect(60, 240, 75, 23))
        self.accept_button.setObjectName("accept_button")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(250, 240, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login.setText(_translate("Dialog", "LOGIN"))
        self.label_2.setText(_translate("Dialog", "is calling."))
        self.accept_button.setText(_translate("Dialog", "Accept"))
        self.pushButton.setText(_translate("Dialog", "Deny"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
