# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'log_reg_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_Register(object):
    def setupUi(self, Login_Register):
        Login_Register.setObjectName("Login_Register")
        Login_Register.resize(400, 300)
        self.title = QtWidgets.QLabel(Login_Register)
        self.title.setGeometry(QtCore.QRect(36, 10, 321, 41))
        self.title.setObjectName("title")
        self.label_log_in = QtWidgets.QLabel(Login_Register)
        self.label_log_in.setGeometry(QtCore.QRect(110, 70, 47, 13))
        self.label_log_in.setObjectName("label_log_in")
        self.label_register = QtWidgets.QLabel(Login_Register)
        self.label_register.setGeometry(QtCore.QRect(300, 70, 47, 13))
        self.label_register.setObjectName("label_register")
        self.label_login = QtWidgets.QLabel(Login_Register)
        self.label_login.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.label_login.setObjectName("label_login")
        self.label_password = QtWidgets.QLabel(Login_Register)
        self.label_password.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_password.setObjectName("label_password")
        self.label_email = QtWidgets.QLabel(Login_Register)
        self.label_email.setGeometry(QtCore.QRect(10, 210, 47, 13))
        self.label_email.setObjectName("label_email")
        self.log_line_login = QtWidgets.QLineEdit(Login_Register)
        self.log_line_login.setGeometry(QtCore.QRect(70, 110, 113, 20))
        self.log_line_login.setObjectName("log_line_login")
        self.log_line_password = QtWidgets.QLineEdit(Login_Register)
        self.log_line_password.setGeometry(QtCore.QRect(70, 160, 113, 20))
        self.log_line_password.setObjectName("log_line_password")
        self.reg_line_login = QtWidgets.QLineEdit(Login_Register)
        self.reg_line_login.setGeometry(QtCore.QRect(270, 110, 113, 20))
        self.reg_line_login.setObjectName("reg_line_login")
        self.reg_line_password = QtWidgets.QLineEdit(Login_Register)
        self.reg_line_password.setGeometry(QtCore.QRect(270, 160, 113, 20))
        self.reg_line_password.setObjectName("reg_line_password")
        self.reg_line_email = QtWidgets.QLineEdit(Login_Register)
        self.reg_line_email.setGeometry(QtCore.QRect(270, 210, 113, 20))
        self.reg_line_email.setObjectName("reg_line_email")
        self.button_reg = QtWidgets.QPushButton(Login_Register)
        self.button_reg.setGeometry(QtCore.QRect(300, 270, 75, 23))
        self.button_reg.setObjectName("button_reg")
        self.button_log = QtWidgets.QPushButton(Login_Register)
        self.button_log.setGeometry(QtCore.QRect(210, 270, 75, 23))
        self.button_log.setObjectName("button_log")
        self.button_settings = QtWidgets.QPushButton(Login_Register)
        self.button_settings.setGeometry(QtCore.QRect(20, 270, 75, 23))
        self.button_settings.setObjectName("button_settings")

        self.retranslateUi(Login_Register)
        QtCore.QMetaObject.connectSlotsByName(Login_Register)

    def retranslateUi(self, Login_Register):
        _translate = QtCore.QCoreApplication.translate
        Login_Register.setWindowTitle(_translate("Login_Register", "Dialog"))
        self.title.setText(_translate("Login_Register", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#00ff00;\">Your Chat</span></p></body></html>"))
        self.label_log_in.setText(_translate("Login_Register", "Log in:"))
        self.label_register.setText(_translate("Login_Register", "Register:"))
        self.label_login.setText(_translate("Login_Register", "login:"))
        self.label_password.setText(_translate("Login_Register", "password:"))
        self.label_email.setText(_translate("Login_Register", "email:"))
        self.button_reg.setText(_translate("Login_Register", "Register"))
        self.button_log.setText(_translate("Login_Register", "Log in"))
        self.button_settings.setText(_translate("Login_Register", "Settings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Register = QtWidgets.QDialog()
    ui = Ui_Login_Register()
    ui.setupUi(Login_Register)
    Login_Register.show()
    sys.exit(app.exec_())
