# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'response_windows.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(424, 181)
        self.short_label = QtWidgets.QLabel(Dialog)
        self.short_label.setGeometry(QtCore.QRect(130, 10, 151, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.short_label.setFont(font)
        self.short_label.setObjectName("short_label")
        self.long_label = QtWidgets.QLabel(Dialog)
        self.long_label.setGeometry(QtCore.QRect(60, 110, 281, 31))
        self.long_label.setObjectName("long_label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.short_label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">TextLabel</p></body></html>"))
        self.long_label.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
